CREATE TABLE user (
  ID INTEGER(11) AUTO_INCREMENT PRIMARY KEY ,
  FirstName VARCHAR(50) NOT NULL ,
  LastName VARCHAR(50) NOT NULL,
  Email VARCHAR(50) NOT NULL ,
  PassWord VARCHAR(50) NOT NULL ,
  Gender VARCHAR(10) NOT NULL ,
  BirthDay DATE NOT NULL
);